import fs from "fs";
import path from "path";

/**
 * Generate `theta-actors.d.ts` in the Vite project root so TypeScript
 * can resolve `import { ... } from 'theta:actors'` via tsconfig `paths`.
 *
 * The generated file re-exports everything from the wasm-pack .d.ts.
 * Users must add `"theta:actors": ["./theta-actors.d.ts"]` to tsconfig paths.
 */
export function generateTypeDeclaration(
  projectRoot: string,
  pkgDir: string,
  moduleName: string
): void {
  // Use .js for path — bundler moduleResolution finds the adjacent .d.ts
  let relJs = path
    .relative(projectRoot, path.join(pkgDir, `${moduleName}.js`))
    .replace(/\\/g, "/");
  if (!relJs.startsWith(".")) {
    relJs = "./" + relJs;
  }

  // export * covers named exports; export { default } covers the init() default
  // initTheta is injected by the virtual module — declare it here so TS sees it.
  const content = `// Auto-generated by vite-plugin-theta — do not edit
export * from '${relJs}';
export { default } from '${relJs}';
/** Initialise the Theta WASM runtime (wasm-bindgen init + iroh endpoint). Returns the local peer public key. */
export declare function initTheta(): Promise<string>;
`;

  fs.writeFileSync(path.join(projectRoot, "theta-actors.d.ts"), content);
}
