import fs from "fs";
import path from "path";

const UMBRELLA_PKG_NAME = "theta-ts-umbrella";
const UMBRELLA_PKG_NAME_UNDERSCORE = "theta_ts_umbrella";

/**
 * Read `[package].name` from a Cargo.toml.
 * Returns the raw name (with hyphens).
 */
export function readCratePackageName(cratePath: string): string {
  const cargoToml = fs.readFileSync(
    path.join(cratePath, "Cargo.toml"),
    "utf8"
  );
  const match = cargoToml.match(/^\s*name\s*=\s*"([^"]+)"/m);
  if (!match) {
    throw new Error(
      `[theta] Could not find [package].name in ${cratePath}/Cargo.toml`
    );
  }
  return match[1];
}

/**
 * Read `[package].edition` from a Cargo.toml. Defaults to "2021".
 */
function readCrateEdition(cratePath: string): string {
  const cargoToml = fs.readFileSync(
    path.join(cratePath, "Cargo.toml"),
    "utf8"
  );
  const match = cargoToml.match(/^\s*edition\s*=\s*"([^"]+)"/m);
  return match ? match[1] : "2021";
}

export interface UmbrellaCrateEntry {
  /** Absolute path to the sub-crate directory. */
  cratePath: string;
  /** wasm-pack --features to enable for this crate. */
  features: string;
}

/**
 * Generates an umbrella Rust crate at `umbrellaDir` that re-exports all
 * sub-crates. Returns the umbrella's module name (for wasm-pack output).
 *
 * The generated structure:
 *   <umbrellaDir>/Cargo.toml
 *   <umbrellaDir>/src/lib.rs
 */
export function generateUmbrellaCrate(
  umbrellaDir: string,
  entries: UmbrellaCrateEntry[]
): string {
  fs.mkdirSync(path.join(umbrellaDir, "src"), { recursive: true });

  const deps = entries
    .map((e) => {
      const name = readCratePackageName(e.cratePath);
      const relPath = path
        .relative(umbrellaDir, e.cratePath)
        .replace(/\\/g, "/");
      const featuresLine =
        e.features.trim()
          ? `\nfeatures = [${e.features
              .split(",")
              .map((f) => `"${f.trim()}"`)
              .join(", ")}]`
          : "";
      return `[dependencies.${name}]\npath = "${relPath}"${featuresLine}`;
    })
    .join("\n\n");

  // Read edition from first crate; fall back to "2021"
  const edition = entries.length > 0 ? readCrateEdition(entries[0].cratePath) : "2021";

  const cargoToml = `# Auto-generated by vite-plugin-theta — do not edit
[package]
name = "${UMBRELLA_PKG_NAME}"
version = "0.1.0"
edition = "${edition}"

[lib]
crate-type = ["cdylib", "rlib"]

${deps}

# wasm-bindgen must be a direct dep for its proc-macro expansion to resolve correctly
[dependencies.wasm-bindgen]
version = "0.2"

# Prevent interference with the outer Rust workspace
[workspace]

# wasm-opt can fail on incremental builds; theta-ts uses rollup/vite instead
[package.metadata.wasm-pack.profile.release]
wasm-opt = false
`;

  const libRs = entries
    .map((e) => {
      const name = readCratePackageName(e.cratePath);
      const ident = name.replace(/-/g, "_");
      return `pub use ${ident}::*;`;
    })
    .join("\n");

  const libRsContent = `// Auto-generated by vite-plugin-theta — do not edit\n${libRs}\n`;

  fs.writeFileSync(path.join(umbrellaDir, "Cargo.toml"), cargoToml);
  fs.writeFileSync(path.join(umbrellaDir, "src", "lib.rs"), libRsContent);

  return UMBRELLA_PKG_NAME_UNDERSCORE;
}
